### ISSUE TITLE
Why are control chars in attribute values considered unsafe?

### ISSUE THREAD

**Issue by npruehs** [nolimitdev/vue-html-secure#1]
Hey @nolimitdev!

Thanks for your plugin! It's great to see some simple security measures being put into a small plugin instead a huge library.

We've been wondering: Why are control chars, as handled in commit cabe881c63820a9f88b7c18047e04881c907d7a9, considered unsafe? Can you provide a short explanation and/or a reference for this? We love the examples for the other security measures you've implemented, but are unsure about this one.

Thanks for your help!
Nick

**Comment by nolimitdev** [comment]
Hi, sorry for late reply. Control chars before `javascript:...` are unsafe when searching `javascript:` at the begining of string by `attributeValue.indexOf('javascript:') == 0`. That commit is to pass test with this malicious code...

```
<a href=' javascript:alert(5)'>CLICK</a>
<a href='&#xA0javascript:alert(6)'>CLICK</a>
<a href='&#x1680;javascript:alert(7)'>CLICK</a>
<a href='&#x180E;javascript:alert(8)'>CLICK</a>
<a href='&#x2000;javascript:alert(9)'>CLICK</a>
<a href='&#x2001;javascript:alert(10)'>CLICK</a>
<a href='&#x2002;javascript:alert(11)'>CLICK</a>
<a href='&#x2003;javascript:alert(12)'>CLICK</a>
<a href='&#x2004;javascript:alert(13)'>CLICK</a>
<a href='&#x2005;javascript:alert(14)'>CLICK</a>
<a href='&#x2006;javascript:alert(15)'>CLICK</a>
<a href='&#x2006;javascript:alert(16)'>CLICK</a>
<a href='&#x2007;javascript:alert(17)'>CLICK</a>
<a href='&#x2008;javascript:alert(18)'>CLICK</a>
<a href='&#x2009;javascript:alert(19)'>CLICK</a>
<a href='&#x200A;javascript:alert(20)'>CLICK</a>
<a href='&#x200B;javascript:alert(21)'>CLICK</a>
<a href='&#x205f;javascript:alert(22)'>CLICK</a>
<a href='&#x3000;javascript:alert(23)'>CLICK</a>
```
